app:
  name: "web-api-server"
  addr: ":8081"


  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600
  #  路由全局前缀
  router-prefix: ""

mysql:
  host: "127.0.0.1"
  port: "3306"
  database: "ts_1"
  username: "root"
  password: "root"
  charset: "utf8mb4"
  maxIdleConns: 10
  maxOpenConns: 100
  logMode: "info"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  username: ""
  port: 6379
  db: 1

jwt:
  signingKey: '121eweqwe2312esa'
  expiresTime: 86400
  buffer-time: 1d
  issuer: '121eweqwe2312esa'

local:
  path: public/uploads
  store-path: public/file

log:
  BaseDirectoryName: 'runtime/logs'
  InfoDirectoryName: 'info'
  WarnDirectoryName: "warn"
  ErrorDirectoryName: "error"
  DebugDirectoryName: "debug"
  InfoFileName: "info.log"
  WarnFileName: "warn.log"
  ErrorFileName: "error.log"
  DebugFileName: "debug.log"
  LogFileMaxSize: 128
  LogFileMaxBackups: 180
  LogFileMaxAge: 1
  LogFileCompress: true
  LogConsoleOut: true
